version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./ocomon:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ocomon_6
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: ocomonuser
      MYSQL_PASSWORD: ocomonpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
